language: go
go:
 - 1.7.3

services:
 - docker
 
script:
  - go test -v -tags=integration ./...

after_success:
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - ./coverage.bash
  - goveralls -coverprofile gover.coverprofile -service drone.io -repotoken $COVERALLS_TOKEN
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o UIHostService main.go
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO_NAME_EXTENSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo ""; else echo -$TRAVIS_BRANCH ; fi`
  - export REPO=microbusiness/uihost-service$REPO_NAME_EXTENSION
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO .
  - docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
